### PR TITLE
Healing ability

### LINKED ISSUE #280: player healing ability

### PR DESCRIPTION
**Pull request by poetahto**
- Added new healing ability for the player, which can heal a configurable amount of health after the heal key has been held for a configurable amount of time. It also has a cool camera zoom effect.
- Created a camera controller singleton for identifying the currently active camera and applying effects to it.

Closes #280

### CODE REVIEW

**Review by BUNN1E5 — CHANGES_REQUESTED** [review]
I seem to be getting a Null Reference Exception on line 89 where you use do some GUI stuff. When removing that to stop the errors, I still cant get it to work

**Review by Kainkun — APPROVED** [review]
coolio

**Review by BUNN1E5 — APPROVED** [review]
Looks good and seems like it works! I'm gonna let you handle the merge conflict stuff since you prob know what is the correct code

**Review by Kainkun — APPROVED** [review]
lgtm

**Pull request merged**
