### PR TITLE
Finalized Fireball Lock and Key design 

### LINKED ISSUE #210: 4. fireball lock and key area
- [x] one way entrance
- [x] lock area
- [x] key area
- [x] exit
image

### PR DESCRIPTION
**Pull request by Exopl0x**
Closes #210

Based on my concept design: #73 

Level is in branch: 4-Fireball-lock-and-key-level

Scene to load: 4FireBallLockKey

Player starting point is where "TempPlayer" is now, Slide and Bash aren't implemented yet so just move the player into wherever they are supposed to go. (Past slide tunnel just after a small jump, and after the player is supposed to Bash the enemy inside "The Pit" to get to the open platform to get to the Torch prop, which is supposed to represent the Fireball ability.)

Fireball ability is then used to either go back to where the player came from, or up to the top-left or top-right for two potential exits, or to skip the Slide tunnel in the event of backtracking.

### CODE REVIEW

**Comment by Exopl0x** [comment]
FireballLockAndKey

Teaches player to Vertically fireball boost, Horizontally fireball boost, and diagonally fireball boost.

**Review by Kainkun — CHANGES_REQUESTED** [review]
go ahead and add that platform on the bottom. also update from main to get a feel more the new player movement

**Review by Kainkun — APPROVED** [review]
great start :)

**Comment by Kainkun** [comment]
image
Here are some of my opinions. I think the frog is in too tight of an area to have a good combat encounter. maybe you can create a bigger platform for combat. Also the mana tree and the god shouldn't be overlapping

**Comment by Kainkun** [comment]
oh and maybe flatten some areas

**Pull request merged**
